### ISSUE TITLE
How do you build V8 to standalone static library ?

### ISSUE THREAD

**Issue by cmzy** [hyperandroid/CompiledV8#1]
How do you build V8 to standalone static library ? Could you post your step?

Thanks!

**Comment by cmzy** [comment]
I build it (8.0) and get so many .a file, How do I make it standalone?


-rw-r--r-- 1 andyzhang andyzhang       784 Feb 21 13:18 libfuzzer_support.a
-rw-r--r-- 1 andyzhang andyzhang       240 Feb 21 13:18 libjson_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang      1314 Feb 21 13:18 libmulti_return_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang       268 Feb 21 13:18 libparser_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang      3830 Feb 21 13:18 libregexp_builtins_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang       354 Feb 21 13:18 libregexp_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang    393498 Feb 21 12:37 libtorque_base.a
-rw-r--r-- 1 andyzhang andyzhang       472 Feb 21 12:41 libtorque_generated_definitions.a
-rw-r--r-- 1 andyzhang andyzhang    507816 Feb 21 12:47 libtorque_generated_initializers.a
-rw-r--r-- 1 andyzhang andyzhang     38132 Feb 21 12:37 libtorque_ls_base.a
-rw-r--r-- 1 andyzhang andyzhang   1692304 Feb 21 12:55 libv8_base_without_compiler.a
-rw-r--r-- 1 andyzhang andyzhang   1106364 Feb 21 12:56 libv8_compiler.a
-rw-r--r-- 1 andyzhang andyzhang   1106804 Feb 21 12:57 libv8_compiler_opt.a
-rw-r--r-- 1 andyzhang andyzhang       496 Feb 21 12:58 libv8_init.a
-rw-r--r-- 1 andyzhang andyzhang    379794 Feb 21 12:58 libv8_initializers.a
-rw-r--r-- 1 andyzhang andyzhang     30172 Feb 21 12:37 libv8_libbase.a
-rw-r--r-- 1 andyzhang andyzhang     28996 Feb 21 12:37 libv8_libplatform.a
-rw-r--r-- 1 andyzhang andyzhang      3942 Feb 21 12:37 libv8_libsampler.a
-rw-r--r-- 1 andyzhang andyzhang 114740834 Feb 21 13:18 libv8_monolith.a
-rw-r--r-- 1 andyzhang andyzhang       792 Feb 21 13:18 libv8_snapshot.a
-rw-r--r-- 1 andyzhang andyzhang      1228 Feb 21 13:18 libwasm_async_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang       722 Feb 21 13:18 libwasm_code_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang       738 Feb 21 13:18 libwasm_compile_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang       240 Feb 21 13:18 libwasm_fuzzer.a
-rw-r--r-- 1 andyzhang andyzhang      3144 Feb 21 12:40 lib_wasm_fuzzer_common.a
-rw-r--r-- 1 andyzhang andyzhang      1566 Feb 21 12:58 libwasm_module_runner.a
-rw-r--r-- 1 andyzhang andyzhang 115440134 Feb 21 13:18 libwee8.a

**Comment by hyperandroid** [comment]
libv8_monolith.a

**Comment by cmzy** [comment]
could you send me more information？

**Comment by hyperandroid** [comment]
you seemed to have compiled already, otherwise you won't have the
libv8_monolith.a in place. That your v8 compiled version. Ready to use.
You also need the header files, if not dealing with inspector, just the
`include` folder.
